from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(AddonProduct)
admin.site.register(AttrGrp)
admin.site.register(Attribute)
admin.site.register(AttributeValueList)
admin.site.register(AttributeValueType)
admin.site.register(Brand)
admin.site.register(Checkout)
admin.site.register(Currency)
admin.site.register(Feature)
admin.site.register(FeatureGrp)
admin.site.register(Language)
admin.site.register(ListedPackage)
admin.site.register(Media)
admin.site.register(PackageType)
admin.site.register(Product)
admin.site.register(ProductCategory)
admin.site.register(ProductDigitalCatalog)
admin.site.register(ProductGroup)
admin.site.register(ProductLanguage)
admin.site.register(ProductMedia)
admin.site.register(ProductPackage)
admin.site.register(ProductSetting)
admin.site.register(ProductSubCategory)
admin.site.register(ProductTaxRate)
admin.site.register(ProductType)
admin.site.register(Status)
admin.site.register(UnitOfMeasure)
admin.site.register(UomType)
admin.site.register(Wishlist)
